csk/urls.py
from django.urls import path
from csk.views import *
app_name='csk'

urlpatterns=[
    path('jaddu/',jaddu,name='jaddu'),
]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb

urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name='rcb'

urlpatterns=[
    path('abd/',abd,name='abd'),
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render


# Create your views here.
def jaddu(request):
    return render(request,'jaddu.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def abd(request):
    return render(request,'abd.html')

templates/abd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>rcb html page</h1>
        <a href="{% url 'csk:jaddu' %}">go to jaddu page</a>


    </center>
</body>
</html>

templates/jaddu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>csk html page</h1>
        <a href="{% url 'rcb:abd' %}">go to abd page</a>


    </center>
</body>
</html>